<?php

declare(strict_types=1);

namespace Nowo\PageBuilderKitBundle\DependencyInjection;

use Nowo\PageBuilderKitBundle\Enum\HtmlSanitizeStrategy;
use Symfony\Component\Config\Definition\Builder\ArrayNodeDefinition;
use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

use function is_string;
use function str_ends_with;
use function str_starts_with;

final class Configuration implements ConfigurationInterface
{
    public const string ALIAS = 'nowo_page_builder_kit';

    public const array CSS_FRAMEWORKS = [
        'bootstrap',
        'bootstrap4',
        'bootstrap5',
        'tabler',
        'tailwind',
        'foundation',
        'custom',
        'none',
    ];

    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder(self::ALIAS);
        /** @var ArrayNodeDefinition $root */
        $root = $treeBuilder->getRootNode();

        $root
            ->children()
                ->scalarNode('default_locale')->defaultValue('es')->end()
                ->arrayNode('locales')
                    ->scalarPrototype()->end()
                    ->defaultValue(['es', 'en'])
                ->end()
                ->arrayNode('security')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('access_roles')
                            ->scalarPrototype()->end()
                            ->defaultValue(['ROLE_EDITOR'])
                        ->end()
                        ->scalarNode('access_checker')->defaultNull()->end()
                        ->booleanNode('allow_unauthenticated')->defaultFalse()->end()
                    ->end()
                ->end()
                ->arrayNode('web_ui')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('path_prefix')
                            ->defaultValue('/admin/page-builder')
                            ->info('URL prefix for all admin UI and document API routes. Public /p/{pageKey} is unaffected. Host should firewall this path.')
                            ->validate()
                                ->ifTrue(static fn (mixed $v): bool => !is_string($v)
                                    || $v === ''
                                    || !str_starts_with($v, '/')
                                    || str_ends_with($v, '/'))
                                ->thenInvalid('web_ui.path_prefix must be a non-empty path starting with "/" and without a trailing slash (e.g. /admin/page-builder).')
                            ->end()
                        ->end()
                        ->scalarNode('layout_template')
                            ->defaultValue('@NowoPageBuilderKitBundle/admin/layout.html.twig')
                        ->end()
                        ->enumNode('css_framework')
                            ->values(self::CSS_FRAMEWORKS)
                            ->defaultValue('tailwind')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('seo')
                    ->addDefaultsIfNotSet()
                    ->info('Defaults for page-level SEO / Open Graph when translation fields are empty.')
                    ->children()
                        ->scalarNode('site_name')->defaultValue('')->end()
                        ->scalarNode('default_og_image')->defaultValue('')->end()
                        ->scalarNode('canonical_base_url')
                            ->defaultValue('')
                            ->info('e.g. https://example.com — builds /p/{slug} when translation.canonicalUrl is empty.')
                        ->end()
                        ->scalarNode('default_robots')->defaultValue('index,follow')->end()
                    ->end()
                ->end()
                ->arrayNode('doctrine')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('table_prefix')->defaultValue('')->end()
                        ->scalarNode('connection')->defaultValue('default')->end()
                    ->end()
                ->end()
                ->arrayNode('html')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->arrayNode('sanitize')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->enumNode('strategy')
                                    ->values(HtmlSanitizeStrategy::values())
                                    ->defaultValue(HtmlSanitizeStrategy::None->value)
                                ->end()
                                ->scalarNode('service')
                                    ->defaultNull()
                                    ->info('Service id implementing PageBuilderHtmlSanitizerInterface when strategy=service.')
                                ->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('revisions')
                    ->addDefaultsIfNotSet()
                    ->info('Optional document version history (BuilderPageRevision snapshots).')
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultFalse()
                            ->info('When true, page saves/publishes can create revision snapshots.')
                        ->end()
                        ->integerNode('max_per_page')
                            ->defaultValue(50)
                            ->min(1)
                            ->info('Oldest revisions are pruned when this limit is exceeded.')
                        ->end()
                        ->booleanNode('on_save')
                            ->defaultTrue()
                            ->info('Snapshot the previous live document before each admin save.')
                        ->end()
                        ->booleanNode('on_publish')
                            ->defaultTrue()
                            ->info('Snapshot the live document when publishing (labeled).')
                        ->end()
                    ->end()
                ->end()
                ->arrayNode('grapesjs')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')->defaultTrue()->end()
                        ->scalarNode('cdn_version')->defaultValue('0.22.9')->end()
                        ->scalarNode('height')->defaultValue('calc(100vh - 220px)')->end()
                        ->booleanNode('allow_scripts')
                            ->defaultFalse()
                            ->info('When true, GrapesJS custom script blocks may be persisted and rendered. XSS risk — keep false unless editors are fully trusted.')
                        ->end()
                        ->booleanNode('allow_custom_code')
                            ->defaultTrue()
                            ->info('Expose Custom HTML / grapesjs-custom-code plugin.')
                        ->end()
                        ->booleanNode('compound_examples')
                            ->defaultTrue()
                            ->info('Expose built-in compound example blocks (Hero, Feature grid, CTA, …).')
                        ->end()
                        ->booleanNode('a11y_helpers')
                            ->defaultTrue()
                            ->info('Expose accessibility traits (aria-*, role, alt) and landmark / skip-link blocks in GrapesJS.')
                        ->end()
                        ->booleanNode('show_devices')->defaultTrue()->end()
                        ->booleanNode('notice_on_unload')->defaultFalse()->end()
                        ->booleanNode('asset_embed_as_base64')->defaultTrue()->end()
                        ->arrayNode('assets_upload')
                            ->addDefaultsIfNotSet()
                            ->info('GrapesJS Asset Manager upload to local disk or third-party storage (e.g. AWS S3).')
                            ->children()
                                ->booleanNode('enabled')->defaultFalse()->end()
                                ->enumNode('storage')
                                    ->values(['local', 's3', 'service'])
                                    ->defaultValue('local')
                                    ->info('local = public filesystem; s3 = core/aws-s3-bundle helper; service = custom PageBuilderAssetStorageInterface.')
                                ->end()
                                ->scalarNode('service')
                                    ->defaultNull()
                                    ->info('Service id implementing PageBuilderAssetStorageInterface when storage=service.')
                                ->end()
                                ->integerNode('max_bytes')->defaultValue(5_242_880)->min(1)->end()
                                ->arrayNode('allowed_mime')
                                    ->scalarPrototype()->end()
                                    ->defaultValue([
                                        'image/jpeg',
                                        'image/png',
                                        'image/gif',
                                        'image/webp',
                                        'image/svg+xml',
                                    ])
                                ->end()
                                ->arrayNode('local')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('directory')
                                            ->defaultValue('%kernel.project_dir%/public/uploads/page-builder')
                                        ->end()
                                        ->scalarNode('public_prefix')
                                            ->defaultValue('/uploads/page-builder')
                                        ->end()
                                    ->end()
                                ->end()
                                ->arrayNode('s3')
                                    ->addDefaultsIfNotSet()
                                    ->children()
                                        ->scalarNode('helper_service')
                                            ->defaultValue('core_aws_s3.service.helper')
                                            ->info('Service id of AwsS3Helper (or compatible).')
                                        ->end()
                                        ->scalarNode('folder')->defaultValue('page-builder')->end()
                                        ->booleanNode('private')
                                            ->defaultFalse()
                                            ->info('false → public-read ACL for <img> URLs in canvas/public render.')
                                        ->end()
                                        ->scalarNode('public_base_url')
                                            ->defaultValue('')
                                            ->info('Optional CDN / CloudFront base URL prepended to the object key.')
                                        ->end()
                                    ->end()
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('twig')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('enabled')
                                    ->defaultTrue()
                                    ->info('Evaluate {{ Twig }} variables inside GrapesJS HTML on public render (sandboxed).')
                                ->end()
                                ->booleanNode('strict_variables')
                                    ->defaultFalse()
                                    ->info('When true, missing Twig variables throw; when false they render empty.')
                                ->end()
                                ->booleanNode('canvas_helpers')
                                    ->defaultTrue()
                                    ->info('Expose Twig variable insert blocks in the GrapesJS Block Manager.')
                                ->end()
                            ->end()
                        ->end()
                        ->arrayNode('canvas_styles')
                            ->scalarPrototype()->end()
                            ->defaultValue([])
                            ->info('CSS URLs injected into the GrapesJS canvas iframe. Empty = derive from web_ui.css_framework.')
                        ->end()
                        ->arrayNode('assets')
                            ->arrayPrototype()
                                ->children()
                                    ->scalarNode('type')->defaultValue('image')->end()
                                    ->scalarNode('src')->isRequired()->end()
                                    ->scalarNode('name')->defaultNull()->end()
                                    ->integerNode('width')->defaultNull()->end()
                                    ->integerNode('height')->defaultNull()->end()
                                ->end()
                            ->end()
                            ->defaultValue([])
                        ->end()
                        ->arrayNode('plugins')
                            ->addDefaultsIfNotSet()
                            ->children()
                                ->booleanNode('preset_webpage')->defaultTrue()->end()
                                ->booleanNode('blocks_basic')->defaultTrue()->end()
                                ->booleanNode('forms')->defaultTrue()->end()
                                ->booleanNode('navbar')->defaultTrue()->end()
                                ->booleanNode('countdown')->defaultTrue()->end()
                                ->booleanNode('export')->defaultTrue()->end()
                                ->booleanNode('tabs')->defaultTrue()->end()
                                ->booleanNode('custom_code')->defaultTrue()->end()
                                ->booleanNode('touch')->defaultTrue()->end()
                                ->booleanNode('parser_postcss')->defaultTrue()->end()
                                ->booleanNode('tooltip')->defaultTrue()->end()
                                ->booleanNode('style_bg')->defaultTrue()->end()
                                ->booleanNode('typed')->defaultTrue()->end()
                                ->booleanNode('tui_image_editor')->defaultTrue()->end()
                            ->end()
                        ->end()
                    ->end()
                ->end()
            ->end();

        return $treeBuilder;
    }
}
